added --dry-run option to ipgem-regen-ifcfg
With this change, the script also applies the configuration vaguely like
a transaction.

diff --git a/gateway/usr/sbin/ipgem-regen-ifcfg b/gateway/usr/sbin/ipgem-regen-ifcfg
--- a/gateway/usr/sbin/ipgem-regen-ifcfg
+++ b/gateway/usr/sbin/ipgem-regen-ifcfg
@@ -6,18 +6,33 @@ set -e -u
 
 myname="$( basename "$0" )"
 hosts=/etc/ipgem-gateway/hosts
-now="$( date '+%F %T')"
-declare -a ifmac=()
+declare -a ifmac=()        # MAC addresses of all IP gateway interfaces
+declare -a modified=()     # Modified config files for dry_run
+declare -a previous_cfg=() # Existing config files (will be deleted/replaced)
 ifcfg=/etc/sysconfig/network-scripts
+new=ipgnew
+dry_run=false
 
-# Cleanup old config files, fill in ifmac[]
+# Argument handling
+case "${1:-}" in
+	"")         ;;
+	--dry-run) dry_run=true ;;
+	*)         echo "Usage: $myname [--dry-run]" 2>&1; exit 1 ;;
+esac
+
+# Cleanup if this script failed earlier
+rm -f "$ifcfg"/*."$new"
+
+# Fill in ifmac[] and previous_cfg[]
 for i in "${!IFNAME[@]}"; do
 	eth="${IFNAME[$i]}"
-	rm -f "$ifcfg/ifcfg-$eth" "$ifcfg/ifcfg-$eth:"*
 	ifmac[$i]="$( ip addr show dev $eth |grep ether |awk '{print $2}' )"
+	existing_cfg+=("$ifcfg/ifcfg-$eth" "$ifcfg/ifcfg-$eth:"*)
 done
+modified+=("${existing_cfg[@]}")
 
-grep -v '^#' "$hosts" |grep '[0-9]' |while read name oldip newip; do
+# For each configured host (in $hosts) to relay
+while read name oldip newip; do
 	# Figure out which eth to use for this host
 	ifidx=
 	for i in "${!IFNAME[@]}"; do
@@ -32,10 +47,11 @@ grep -v '^#' "$hosts" |grep '[0-9]' |while read name oldip newip; do
 	fi
 
 	# Determine if we're defining the parent or sub interface
-	if [ ! -e "$ifcfg/ifcfg-${IFNAME[$ifidx]}" ]; then
+	ifcfg_parent="$ifcfg/ifcfg-${IFNAME[$ifidx]}"
+	if [ ! -e "$ifcfg_parent.$new" ]; then
 		# First host for this network, write the parent config
-		cat >"$ifcfg/ifcfg-${IFNAME[$ifidx]}" <<EOF
-# Generated by $myname on $now, proxy for $name
+		cat >"$ifcfg_parent.$new" <<EOF
+# Generated by $myname, proxy for $name
 DEVICE=${IFNAME[$ifidx]}
 BOOTPROTO=static
 DHCPCLASS=
@@ -45,12 +61,13 @@ PREFIX=${IFPREFIX[$ifidx]}
 ONBOOT=yes
 NM_CONTROLLED=no
 EOF
+		modified+=("$ifcfg_parent")
 	else
 		# Find a free subinterface
 		subif=
 		for (( i = 0; i < 1000; i++ )); do
-			if [ ! -e "$ifcfg/ifcfg-${IFNAME[$ifidx]}:$i" ]; then
-				subif="${IFNAME[$ifidx]}:$i"
+			if [ ! -e "$ifcfg_parent:$i.$new" ]; then
+				subif=":$i"
 				break
 			fi
 		done
@@ -60,15 +77,50 @@ EOF
 		fi
 
 		# Configure it
-		cat >"$ifcfg/ifcfg-$subif" <<EOF
-# Generated by $myname on $now, proxy for $name
-DEVICE=$subif
+		cat >"$ifcfg_parent$subif.$new" <<EOF
+# Generated by $myname, proxy for $name
+DEVICE=${IFNAME[$ifidx]}$subif
 BOOTPROTO=static
 ONPARENT=yes
 IPADDR=$oldip
 PREFIX=${IFPREFIX[$ifidx]}
 NM_CONTROLLED=no
 EOF
+		modified+=("$ifcfg_parent$subif")
 	fi
-done
+done < <( grep -v '^#' "$hosts" |grep '[0-9]' )
 
+# Remove duplicates and sort $modified
+readarray -t modified < <( printf "%s\n" "${modified[@]}" | sort -u )
+
+if $dry_run; then
+	echo "Would perform the following changes:"
+
+	any_change=false
+	for f in "${modified[@]}"; do
+		set +e
+		diff -Nu "$f" "$f.$new"
+		differr=$?
+		set -e
+		case "$differr" in
+			0) ;;
+			1) any_change=true ;;
+			*) echo "diff failed, see error above" >&2; exit 1 ;;
+		esac
+
+		rm -f "$f.$new"
+	done
+
+	if ! $any_change; then
+		echo "Nothing."
+	fi
+
+	exit 0
+fi
+
+# Cleanup old config files (which may not exist in $modified)
+rm -f "${existing_cfg[@]}"
+# Replace the config files with the $new ones
+for f in "${modified[@]}"; do
+	mv -f "$f.$new" "$f"
+done
